// SB Nation blog RSS feeds by team slug
// New path is /rss/index.xml (the old /rss/current no longer works)
export const sbNationFeeds: Record<string, string> = {
  // NFL
  chiefs: 'https://www.arrowheadpride.com/rss/index.xml',
  '49ers': 'https://www.ninersnation.com/rss/index.xml',
  cowboys: 'https://www.bloggingtheboys.com/rss/index.xml',
  eagles: 'https://www.bleedinggreennation.com/rss/index.xml',
  packers: 'https://www.acmepackingcompany.com/rss/index.xml',
  patriots: 'https://www.patspulpit.com/rss/index.xml',
  steelers: 'https://www.behindthesteelcurtain.com/rss/index.xml',
  ravens: 'https://www.baltimorebeatdown.com/rss/index.xml',
  bills: 'https://www.buffalorumblings.com/rss/index.xml',
  seahawks: 'https://www.fieldgulls.com/rss/index.xml',
  bears: 'https://www.windycitygridiron.com/rss/index.xml',
  bengals: 'https://www.cincinnatijungle.com/rss/index.xml',
  broncos: 'https://www.milehighreport.com/rss/index.xml',
  browns: 'https://www.dawgsbynature.com/rss/index.xml',
  buccaneers: 'https://www.bucsration.com/rss/index.xml',
  cardinals: 'https://www.revengeofthebirds.com/rss/index.xml',
  chargers: 'https://www.boltsfromtheblue.com/rss/index.xml',
  colts: 'https://www.stampedeblue.com/rss/index.xml',
  commanders: 'https://www.hogshaven.com/rss/index.xml',
  dolphins: 'https://www.thephinsider.com/rss/index.xml',
  falcons: 'https://www.thefalcoholic.com/rss/index.xml',
  giants: 'https://www.bigblueview.com/rss/index.xml',
  jaguars: 'https://www.bigcatcountry.com/rss/index.xml',
  jets: 'https://www.ganggreennation.com/rss/index.xml',
  lions: 'https://www.prideofdetroit.com/rss/index.xml',
  panthers: 'https://www.catscratchreader.com/rss/index.xml',
  raiders: 'https://www.silverandblackpride.com/rss/index.xml',
  rams: 'https://www.turfshowtimes.com/rss/index.xml',
  saints: 'https://www.canalstreetchronicles.com/rss/index.xml',
  texans: 'https://www.battleredblog.com/rss/index.xml',
  titans: 'https://www.musiccitymiracles.com/rss/index.xml',
  vikings: 'https://www.dailynorseman.com/rss/index.xml',
  // NBA
  lakers: 'https://www.silverscreenandroll.com/rss/index.xml',
  celtics: 'https://www.celticsblog.com/rss/index.xml',
  warriors: 'https://www.goldenstateofmind.com/rss/index.xml',
  knicks: 'https://www.postingandtoasting.com/rss/index.xml',
  heat: 'https://www.hothothoops.com/rss/index.xml',
  bulls: 'https://www.blogabull.com/rss/index.xml',
  nets: 'https://www.netsdaily.com/rss/index.xml',
  bucks: 'https://www.brewhoop.com/rss/index.xml',
  suns: 'https://www.brightsideofthesun.com/rss/index.xml',
  nuggets: 'https://www.denverstiffs.com/rss/index.xml',
  mavericks: 'https://www.mavsmoneyball.com/rss/index.xml',
  '76ers': 'https://www.libertyballers.com/rss/index.xml',
  raptors: 'https://www.raptorshq.com/rss/index.xml',
  cavaliers: 'https://www.fearthesword.com/rss/index.xml',
  thunder: 'https://www.welcometoloudcity.com/rss/index.xml',
  spurs: 'https://www.poundingtherock.com/rss/index.xml',
  hawks: 'https://www.peachtreehoops.com/rss/index.xml',
  clippers: 'https://www.clipsnation.com/rss/index.xml',
  // MLS
  'seattle-sounders': 'https://www.sounderatheart.com/rss/index.xml',
  'portland-timbers': 'https://www.stumptownfooty.com/rss/index.xml',
  'atlanta-united': 'https://www.dirtysouthsoccer.com/rss/index.xml',
}

// ESPN team IDs for the JSON news API
// https://site.api.espn.com/apis/site/v2/sports/{sport}/{league}/news?team={id}
export const espnTeamIds: Record<string, { id: number; sport: string; league: string }> = {
  // NFL
  chiefs: { id: 12, sport: 'football', league: 'nfl' },
  '49ers': { id: 25, sport: 'football', league: 'nfl' },
  cowboys: { id: 6, sport: 'football', league: 'nfl' },
  eagles: { id: 21, sport: 'football', league: 'nfl' },
  packers: { id: 9, sport: 'football', league: 'nfl' },
  patriots: { id: 17, sport: 'football', league: 'nfl' },
  steelers: { id: 23, sport: 'football', league: 'nfl' },
  ravens: { id: 33, sport: 'football', league: 'nfl' },
  bills: { id: 2, sport: 'football', league: 'nfl' },
  seahawks: { id: 26, sport: 'football', league: 'nfl' },
  bears: { id: 3, sport: 'football', league: 'nfl' },
  bengals: { id: 4, sport: 'football', league: 'nfl' },
  broncos: { id: 7, sport: 'football', league: 'nfl' },
  browns: { id: 5, sport: 'football', league: 'nfl' },
  buccaneers: { id: 27, sport: 'football', league: 'nfl' },
  cardinals: { id: 22, sport: 'football', league: 'nfl' },
  chargers: { id: 24, sport: 'football', league: 'nfl' },
  colts: { id: 11, sport: 'football', league: 'nfl' },
  commanders: { id: 28, sport: 'football', league: 'nfl' },
  dolphins: { id: 15, sport: 'football', league: 'nfl' },
  falcons: { id: 1, sport: 'football', league: 'nfl' },
  giants: { id: 19, sport: 'football', league: 'nfl' },
  jaguars: { id: 30, sport: 'football', league: 'nfl' },
  jets: { id: 20, sport: 'football', league: 'nfl' },
  lions: { id: 8, sport: 'football', league: 'nfl' },
  panthers: { id: 29, sport: 'football', league: 'nfl' },
  raiders: { id: 13, sport: 'football', league: 'nfl' },
  rams: { id: 14, sport: 'football', league: 'nfl' },
  saints: { id: 18, sport: 'football', league: 'nfl' },
  texans: { id: 34, sport: 'football', league: 'nfl' },
  titans: { id: 10, sport: 'football', league: 'nfl' },
  vikings: { id: 16, sport: 'football', league: 'nfl' },
  // NBA
  lakers: { id: 13, sport: 'basketball', league: 'nba' },
  celtics: { id: 2, sport: 'basketball', league: 'nba' },
  warriors: { id: 9, sport: 'basketball', league: 'nba' },
  knicks: { id: 18, sport: 'basketball', league: 'nba' },
  heat: { id: 14, sport: 'basketball', league: 'nba' },
  bulls: { id: 4, sport: 'basketball', league: 'nba' },
  nets: { id: 17, sport: 'basketball', league: 'nba' },
  bucks: { id: 15, sport: 'basketball', league: 'nba' },
  suns: { id: 21, sport: 'basketball', league: 'nba' },
  nuggets: { id: 7, sport: 'basketball', league: 'nba' },
  mavericks: { id: 6, sport: 'basketball', league: 'nba' },
  '76ers': { id: 20, sport: 'basketball', league: 'nba' },
  raptors: { id: 28, sport: 'basketball', league: 'nba' },
  cavaliers: { id: 5, sport: 'basketball', league: 'nba' },
  thunder: { id: 25, sport: 'basketball', league: 'nba' },
  spurs: { id: 24, sport: 'basketball', league: 'nba' },
  hawks: { id: 1, sport: 'basketball', league: 'nba' },
  clippers: { id: 12, sport: 'basketball', league: 'nba' },
  grizzlies: { id: 29, sport: 'basketball', league: 'nba' },
  timberwolves: { id: 16, sport: 'basketball', league: 'nba' },
  pelicans: { id: 3, sport: 'basketball', league: 'nba' },
  hornets: { id: 30, sport: 'basketball', league: 'nba' },
  pacers: { id: 11, sport: 'basketball', league: 'nba' },
  magic: { id: 19, sport: 'basketball', league: 'nba' },
  wizards: { id: 27, sport: 'basketball', league: 'nba' },
  pistons: { id: 8, sport: 'basketball', league: 'nba' },
  rockets: { id: 10, sport: 'basketball', league: 'nba' },
  blazers: { id: 22, sport: 'basketball', league: 'nba' },
  jazz: { id: 26, sport: 'basketball', league: 'nba' },
  kings: { id: 23, sport: 'basketball', league: 'nba' },
  // MLS — uses usa.1 league code
  'inter-miami': { id: 10151, sport: 'soccer', league: 'usa.1' },
  'la-galaxy': { id: 96, sport: 'soccer', league: 'usa.1' },
  lafc: { id: 11091, sport: 'soccer', league: 'usa.1' },
  'seattle-sounders': { id: 9726, sport: 'soccer', league: 'usa.1' },
  'atlanta-united': { id: 9002, sport: 'soccer', league: 'usa.1' },
  'portland-timbers': { id: 9498, sport: 'soccer', league: 'usa.1' },
}
