// Team slug → subreddit name(s) for Reddit fetching
// Primary subreddit listed first; secondary is a fallback alias

export const SUBREDDIT_MAP: Record<string, string[]> = {
  // ── NFL ──────────────────────────────────────────
  chiefs: ['KansasCityChiefs'],
  eagles: ['eagles'],
  cowboys: ['cowboys'],
  '49ers': ['49ers'],
  bears: ['CHIBears'],
  bengals: ['bengals'],
  bills: ['buffalobills'],
  broncos: ['DenverBroncos'],
  browns: ['Browns'],
  buccaneers: ['buccaneers'],
  cardinals: ['AZCardinals'],
  chargers: ['Chargers'],
  colts: ['Colts'],
  commanders: ['Commanders'],
  dolphins: ['miamidolphins'],
  falcons: ['falcons'],
  giants: ['NYGiants'],
  jaguars: ['Jaguars'],
  jets: ['nyjets'],
  lions: ['detroitlions'],
  packers: ['GreenBayPackers'],
  panthers: ['panthers'],
  patriots: ['Patriots'],
  raiders: ['raiders'],
  rams: ['LosAngelesRams'],
  ravens: ['ravens'],
  saints: ['Saints'],
  seahawks: ['Seahawks'],
  steelers: ['steelers'],
  texans: ['Texans'],
  titans: ['Tennesseetitans'],
  vikings: ['minnesotavikings'],

  // ── NBA ──────────────────────────────────────────
  lakers: ['lakers'],
  celtics: ['bostonceltics'],
  warriors: ['warriors'],
  bulls: ['chicagobulls'],
  heat: ['heat'],
  nets: ['GoNets'],
  knicks: ['NYKnicks'],
  bucks: ['MkeBucks'],
  suns: ['suns'],
  nuggets: ['denvernuggets'],
  mavericks: ['Mavericks'],
  '76ers': ['sixers'],
  raptors: ['torontoraptors'],
  kings: ['kings'],
  cavaliers: ['clevelandcavs'],
  thunder: ['Thunder'],
  grizzlies: ['memphisgrizzlies'],
  timberwolves: ['timberwolves'],
  pelicans: ['NOLAPelicans'],
  spurs: ['NBASpurs'],
  hawks: ['AtlantaHawks'],
  hornets: ['CharlotteHornets'],
  pacers: ['pacers'],
  magic: ['OrlandoMagic'],
  wizards: ['washingtonwizards'],
  pistons: ['DetroitPistons'],
  rockets: ['rockets'],
  blazers: ['ripcity'],
  jazz: ['UtahJazz'],
  clippers: ['LAClippers'],

  // ── MLS ──────────────────────────────────────────
  'inter-miami': ['InterMiami'],
  'la-galaxy': ['LAGalaxy'],
  lafc: ['LAFC'],
  'seattle-sounders': ['SoundersFC'],
  'portland-timbers': ['timbers'],
  'atlanta-united': ['AtlantaUnited'],
  'austin-fc': ['AustinFC'],
  'cf-montreal': ['montrealimpact'],
  'charlotte-fc': ['CharlotteFC'],
  'chicago-fire': ['chicagofire'],
  'columbus-crew': ['TheMassive'],
  'dc-united': ['DCUnited'],
  'fc-cincinnati': ['FCCincinnati'],
  'fc-dallas': ['fcdallas'],
  'houston-dynamo': ['dynamo'],
  'minnesota-united': ['MinnesotaUnited'],
  'nashville-sc': ['NashvilleSC'],
  'ny-red-bulls': ['rbny'],
  nycfc: ['NYCFC'],
  'orlando-city': ['OCLions'],
  'philadelphia-union': ['PhillyUnion'],
  'real-salt-lake': ['RealSaltLake'],
  'san-diego-fc': ['SanDiegoFC'],
  'san-jose-earthquakes': ['SJEarthquakes'],
  'sporting-kc': ['SportingKC'],
  'st-louis-city': ['stlouiscity'],
  'toronto-fc': ['tfc'],
  'vancouver-whitecaps': ['whitecapsfc'],
  'new-england-revolution': ['newenglandrevolution'],
}
